# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check build.gradle for more details.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for headless machines. See also
# http://www.gradle.org/docs/current/userguide/gradle_daemon.html
# For example, you might specify the total memory, and disable the overhead of offloading to CPU for tasks.
# Gradle tasks are heavier; see https://docs.gradle.org/current/userguide/performance_tuning.html#parallel_execution
# org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=heap-dumps
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds/#sec:decoupled_projects
# org.gradle.parallel=true
# AndroidX package structure to make it unambiguous which package is being used
android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
# Enable the new kotlin plugin DSL
org.gradle.unsafe.concurrent=true
